#!/bin/sh

# This is bound to Shift+PrintScreen by default, requires maim. It lets you
# choose the kind of screenshot to take, including copying the image or even
# highlighting an area to copy. scrotcucks on suicidewatch right now.

case "$(printf "selezione\\nfinestra corrente\\nschermo intero\\nselezione (copia)\\nfinestra corrente (copia)\\nschermo intero (copia)" | dmenu -c -o .8 -dim .4 -l 6 -i -p "Foto dello schermo")" in
	"selezione") maim -s pic-selected-"$(date '+%y%m%d-%H%M-%S').png" ;;
	"finestra corrente") maim -i "$(xdotool getactivewindow)" pic-window-"$(date '+%y%m%d-%H%M-%S').png" ;;
	"schermo intero") maim pic-full-"$(date '+%y%m%d-%H%M-%S').png" ;;
	"selezione (copia)") maim -s | xclip -selection clipboard -t image/png ;;
	"finestra corrente (copia)") maim -i "$(xdotool getactivewindow)" | xclip -selection clipboard -t image/png ;;
	"schermo intero (copia)") maim | xclip -selection clipboard -t image/png ;;
esac
