#!/bin/sh

TOKEN="43cb0742a7a56dfb332002df7e4268d878504e6d"

notifications=$(curl -fs https://api.github.com/notifications?access_token=$TOKEN | jq ".[].unread" | grep -c true)

if [ "$notifications" -gt 0 ]; then
    echo " $notifications"
else
    echo ""
fi
