#!/bin/env sh

players=($(playerctl -l))
oneplayer=FALSE
if [ ${#players[@]} -eq 1 ]
then
    oneplayer=TRUE
    player="mpd"
fi

if [ $oneplayer == FALSE ]
then
    savedplayer=$(cat ~/.scripts/selected_player)
    player_status=$(playerctl -p $savedplayer status 2> /dev/null)

    if [[ ($savedplayer == "mpd") && ($player_status != "Stopped") ]];
    then
        player="mpd"
    else
        found=FALSE

        for item in ${players[*]}
        do
            if [[ ($item == $savedplayer) && ($item != "mpd") ]];
            then
                player=$savedplayer
                found=TRUE
            fi
        done

        if [ $found == FALSE ]
        then
            for item in ${players[*]}
            do
                if [[ $item != "mpd" ]];
                then
                    player=$item
                fi
            done
        fi
    fi
fi

player_status=$(playerctl -p $player status 2> /dev/null)
metadata=($(playerctl -p $player metadata))
foundartist=FALSE
foundalbum=FALSE

for item in ${metadata[*]}
do
    if [[ $item == "xesam:artist" ]];
    then
        foundartist=TRUE
    fi
done

for item in ${metadata[*]}
do
    if [[ $item == "xesam:album" ]];
    then
        foundalbum=TRUE
    fi
done

len="$(playerctl -p $player metadata mpris:length)"
length=$(~/.scripts/convert_time $len)

if [ $foundartist == TRUE ]
then
    if [ "$player_status" = "Playing" ]; then
        pos="$(playerctl -p $player position)"
        position=$(~/.scripts/convert_time $pos)
        echo "$(playerctl -p $player metadata artist) - $(playerctl -p $player metadata title)  -  $position / $length"
    elif [ "$player_status" = "Paused" ]; then
        echo "$(playerctl -p $player metadata artist) - $(playerctl -p $player metadata title)"
    else
        echo " "
    fi
elif [ $foundalbum == TRUE ]
then
    if [ "$player_status" = "Playing" ]; then
        pos="$(playerctl -p $player position)"
        position=$(~/.scripts/convert_time $pos)
        echo "$(playerctl -p $player metadata album) - $(playerctl -p $player metadata title)  -  $position / $length"
    elif [ "$player_status" = "Paused" ]; then
        echo "$(playerctl -p $player metadata album) - $(playerctl -p $player metadata title)"
    else
        echo " "
    fi
else
    if [ "$player_status" = "Playing" ]; then
        pos="$(playerctl -p $player position)"
        position=$(~/.scripts/convert_time $pos)
        echo "$(playerctl -p $player metadata title)  -  $position / $length"
    elif [ "$player_status" = "Paused" ]; then
        echo "$(playerctl -p $player metadata title)"
    else
        echo " "
    fi
fi

