#!/bin/sh
pkill polybar
xrandr --output HDMI-1 --auto --right-of eDP-1
sleep 5
polybar top -r &
~/.scripts/paswitch
feh --bg-fill ~/.config/i3/001.png
sleep 5
polybar hdmi -c ~/.config/polybar/config-hdmi &
feh --bg-fill ~/.config/i3/001.png
