#!/bin/env sh

device=$(xinput | grep Synaptics | awk '{ print $5 }' | awk -F '=' '{ print $2 }')

enabled=$(xinput list-props $device | grep  "Device Enabled" | awk '{ print $4 }')

if [ $enabled -eq 1 ]
then
    xinput disable $device
else
    xinput enable $device
fi
