#!/bin/env sh

# CONFIGURATION
LOCATION=0
YOFFSET=0
XOFFSET=0
WIDTH=68
WIDTH_WIDE=88
THEME=sidebar

rofi -sep "|" -show window -i -p "$1" -location $LOCATION -yoffset $YOFFSET -xoffset $XOFFSET -theme $THEME -width $WIDTH -hide-scrollbar -line-padding 4 -padding 20
